### ISSUE TITLE
Simplify PEPS type

### ISSUE THREAD

**Issue by mtfishman** [LinjianMa/PEPSAD.jl#1]
Just a small thing, but we can use the size of the matrix storage of the PEPS to determine the size of the PEPS, so we could remove the `dimx` and `dimy` fields: https://github.com/LinjianMa/PEPSAD.jl/blob/9444e4e808e6cbb6cd26b6e3ea117fcb05c963e7/src/peps.jl#L8-L9

**Comment by LinjianMa** [comment]
Sounds good, done
